"""Tests for Chunk 7 — Review/export gate integrity.

Verifies:
- Force-export writes a ``force_export`` audit event to EventStore
- Normal export only exports APPROVED artifacts
- Every bypass is loudly recorded (sovereign override audit trail)
- Force-export result includes bypass metadata (force_bypass, force_bypass_state, etc.)
- Project export with --include-unreviewed records audit events for each non-APPROVED artifact
- Project export result includes sovereign_override_count
- N+1 query fix: batch reads work for review_list, review_list_by_type, export_project, review_sources
- review_show reports honest export eligibility (only APPROVED is truly eligible)
- CLI --force warning and confirmation are present
- CLI --reason option is available and flows to backend
"""

from __future__ import annotations

import os
import tempfile

import pytest

from aip.adapter.artifact_store_versioned import VersionedArtifactStore
from aip.adapter.ecs_store_persistent import PersistentEcsStore
from aip.adapter.event_store_queryable import QueryableEventStore
from aip.adapter.project.sqlite_project_store import SqliteProjectStore
from aip.orchestration.review_export_pipeline import (
    ReviewExportStores,
    export_artifact,
    export_project,
    review_approve,
    review_list,
    review_list_by_type,
    review_reject,
    review_show,
    review_sources,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


async def _create_test_stores(tmp_dir: str) -> ReviewExportStores:
    """Create ReviewExportStores with real persistent SQLite stores."""
    db_path = os.path.join(tmp_dir, "aip.db")

    artifact_store = VersionedArtifactStore(db_path)
    await artifact_store.initialize()

    event_store = QueryableEventStore(db_path)
    await event_store.initialize()

    project_store = SqliteProjectStore(db_path)
    await project_store.initialize()

    ecs_store = PersistentEcsStore(db_path, event_store=event_store)
    await ecs_store.initialize()

    return ReviewExportStores(
        artifact_store=artifact_store,
        ecs_store=ecs_store,
        event_store=event_store,
        project_store=project_store,
    )


async def _create_project_and_artifact(
    stores: ReviewExportStores,
    project_name: str = "test_project",
    artifact_id: str = "ask:abc123test",
    content: str = "This is a generated answer about AIP architecture.",
    source_ids: list[str] | None = None,
    source_types: list[str] | None = None,
    empty: bool = False,
) -> str:
    """Create a project and a GENERATED artifact (simulating ask --save-artifact).

    Returns the artifact_id.
    """
    # Create project
    await stores.project_store.create_project(project_name, project_name, domain=project_name)

    # Write artifact
    metadata = {
        "artifact_type": "ask_answer",
        "project_id": project_name,
        "project_name": project_name,
        "prompt": "What is the AIP architecture?",
        "model_slot": "synthesis",
        "model_name": "test-model",
        "source_ids": source_ids if source_ids is not None else ["chunk:conv1:0", "chunk:conv1:1"],
        "source_types": source_types if source_types is not None else ["conversation_chunk", "conversation_chunk"],
        "session_id": "ask:test-session",
        "generated_at": "2025-01-15T10:00:00+00:00",
    }

    artifact_content = "" if empty else content
    await stores.artifact_store.write(artifact_id, artifact_content, metadata)

    # ECS transition: None → GENERATED
    await stores.ecs_store.transition(
        artifact_id=artifact_id,
        from_state=None,
        to_state="GENERATED",
        actor="ask_pipeline",
        reason="Generated by ask pipeline — pending DEFINER review",
    )

    return artifact_id


# ---------------------------------------------------------------------------
# Force-export audit trail tests
# ---------------------------------------------------------------------------


class TestForceExportAuditTrail:
    """Force-export must write an audit event to EventStore."""

    async def test_force_export_generates_audit_event(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(
                aid, out_path, stores, force=True, force_reason="Emergency debug export"
            )

            assert "error" not in result
            assert result.get("force_bypass") is True

            # Verify audit event was written
            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="force_export",
            )
            assert len(events) >= 1
            audit_event = events[0]
            assert audit_event.event_type == "force_export"
            assert audit_event.metadata.get("bypassed_state") == "GENERATED"
            assert "Emergency debug export" in audit_event.metadata.get("reason", "")

    async def test_force_export_without_reason_records_default(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores, force=True)

            assert "error" not in result

            # Audit event should exist with default reason
            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="force_export",
            )
            assert len(events) >= 1
            assert "(no explicit reason provided)" in events[0].metadata.get("reason", "")

    async def test_force_export_rejected_records_audit(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            # Reject the artifact
            await review_reject(aid, stores, note="Bad quality")

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(
                aid, out_path, stores, force=True, force_reason="Debug: inspect rejected artifact"
            )

            assert "error" not in result
            assert result.get("force_bypass_state") == "REJECTED"

            # Verify audit event
            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="force_export",
            )
            assert len(events) >= 1
            assert events[0].metadata.get("bypassed_state") == "REJECTED"

    async def test_approved_export_no_audit_event(self):
        """Normal export of APPROVED artifact should NOT generate a force_export audit event."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            # Approve the artifact
            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores)

            assert "error" not in result
            assert result.get("force_bypass") is None  # No bypass

            # No force_export event should exist
            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="force_export",
            )
            assert len(events) == 0


class TestForceExportResultMetadata:
    """Force-export result must include bypass metadata."""

    async def test_force_export_result_includes_bypass_fields(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(
                aid, out_path, stores, force=True, force_reason="Testing"
            )

            assert result.get("force_bypass") is True
            assert result.get("force_bypass_state") == "GENERATED"
            assert result.get("force_reason") == "Testing"
            assert result.get("audit_recorded") is True

    async def test_normal_export_result_no_bypass_fields(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)
            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores)

            assert "force_bypass" not in result
            assert "force_bypass_state" not in result
            assert "audit_recorded" not in result


# ---------------------------------------------------------------------------
# Export gate integrity — normal export only APPROVED
# ---------------------------------------------------------------------------


class TestExportGateIntegrity:
    """Normal export must refuse non-APPROVED artifacts; force must be explicit."""

    async def test_generated_blocked_without_force(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores, force=False)

            assert "error" in result
            assert result["error"]["code"] == "UNREVIEWED_ARTIFACT"
            assert "sovereign override" in result["error"]["message"].lower()

    async def test_reviewed_blocked_without_force(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            # Transition to REVIEWED (manually set, since normally this happens via review)
            await stores.ecs_store.transition(
                artifact_id=aid,
                from_state="GENERATED",
                to_state="REVIEWED",
                actor="definer",
                reason="Manual review gate pass",
            )

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores, force=False)

            assert "error" in result
            assert result["error"]["code"] == "UNREVIEWED_ARTIFACT"

    async def test_rejected_blocked_without_force(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)
            await review_reject(aid, stores, note="Bad")

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores, force=False)

            assert "error" in result
            assert result["error"]["code"] == "REJECTED_ARTIFACT"
            assert "sovereign override" in result["error"]["message"].lower()

    async def test_approved_exported_without_force(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)
            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores, force=False)

            assert "error" not in result
            assert os.path.exists(out_path)


# ---------------------------------------------------------------------------
# Project export with sovereign override audit
# ---------------------------------------------------------------------------


class TestProjectExportSovereignOverride:
    """Project export with --include-unreviewed records audit for each bypass."""

    async def test_project_export_unreviewed_records_audit(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            # Create two artifacts: one approved, one unreviewed
            aid1 = await _create_project_and_artifact(
                stores, artifact_id="ask:approved1", content="Approved answer 1"
            )
            aid2 = await _create_project_and_artifact(
                stores, artifact_id="ask:unreviewed1", content="Unreviewed answer 1"
            )
            await review_approve(aid1, stores)
            # aid2 stays in GENERATED state

            out_path = os.path.join(tmp, "project_export.md")
            result = await export_project(
                "test_project", out_path, stores,
                include_unreviewed=True,
                force_reason="Debug review before formal approval",
            )

            assert "error" not in result
            assert result["artifacts_exported"] == 2
            assert result.get("sovereign_override_count") == 1
            assert result.get("audit_recorded") is True

            # Verify audit event for unreviewed artifact
            events = await stores.event_store.query(
                artifact_id=aid2,
                event_type="force_export",
            )
            assert len(events) >= 1
            assert events[0].metadata.get("bypassed_state") == "GENERATED"

    async def test_project_export_approved_only_no_audit(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid1 = await _create_project_and_artifact(
                stores, artifact_id="ask:approved1", content="Approved answer 1"
            )
            await review_approve(aid1, stores)

            out_path = os.path.join(tmp, "project_export.md")
            result = await export_project("test_project", out_path, stores)

            assert "error" not in result
            assert result.get("sovereign_override_count") is None

            # No force_export events
            events = await stores.event_store.query(event_type="force_export")
            assert len(events) == 0

    async def test_project_export_markdown_includes_override_marker(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid1 = await _create_project_and_artifact(
                stores, artifact_id="ask:approved1", content="Approved answer 1"
            )
            aid2 = await _create_project_and_artifact(
                stores, artifact_id="ask:unreviewed1", content="Unreviewed answer 1"
            )
            await review_approve(aid1, stores)

            out_path = os.path.join(tmp, "project_export.md")
            await export_project(
                "test_project", out_path, stores,
                include_unreviewed=True,
                force_reason="Debug",
            )

            with open(out_path) as f:
                content = f.read()

            # Sovereign override markers should appear
            assert "SOVEREIGN OVERRIDE" in content
            assert "sovereign overrides: 1" in content.lower()


# ---------------------------------------------------------------------------
# N+1 query fix verification
# ---------------------------------------------------------------------------


class TestBatchQueryPerformance:
    """Verify that batch reads work correctly for review/export flows.

    These tests verify correctness, not performance. The performance
    improvement is structural (N+1 queries → batch reads).
    """

    async def test_review_list_with_multiple_artifacts(self):
        """review_list should work correctly with batch metadata reads."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            # Create multiple artifacts
            for i in range(5):
                await _create_project_and_artifact(
                    stores,
                    artifact_id=f"ask:artifact_{i}",
                    content=f"Answer {i}",
                )

            result = await review_list("test_project", stores)

            assert "error" not in result
            assert len(result["artifacts"]) == 5
            # All should be in GENERATED state
            for art in result["artifacts"]:
                assert art["lifecycle_state"] == "GENERATED"

    async def test_review_list_by_type_with_multiple_artifacts(self):
        """review_list_by_type should work correctly with batch metadata reads."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            for i in range(3):
                await _create_project_and_artifact(
                    stores,
                    artifact_id=f"ask:artifact_{i}",
                    content=f"Answer {i}",
                )

            result = await review_list_by_type("ask_answer", stores)

            assert "error" not in result
            assert len(result["artifacts"]) == 3

    async def test_export_project_batch_reads(self):
        """export_project should work correctly with batch content+metadata reads."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            for i in range(4):
                aid = await _create_project_and_artifact(
                    stores,
                    artifact_id=f"ask:artifact_{i}",
                    content=f"Answer {i} with substantial content for export",
                )
                await review_approve(aid, stores)

            out_path = os.path.join(tmp, "project_export.md")
            result = await export_project("test_project", out_path, stores)

            assert "error" not in result
            assert result["artifacts_exported"] == 4

    async def test_review_sources_batch_reads(self):
        """review_sources should work correctly with batch source lookups."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            # Create source artifacts first
            for sid in ["chunk:conv1:0", "chunk:conv1:1"]:
                await stores.artifact_store.write(
                    sid,
                    f"Source content for {sid}",
                    {"source_file": f"{sid}.txt", "conversation_id": "conv1"},
                )

            aid = await _create_project_and_artifact(
                stores,
                source_ids=["chunk:conv1:0", "chunk:conv1:1"],
                source_types=["conversation_chunk", "conversation_chunk"],
            )

            result = await review_sources(aid, stores)

            assert "error" not in result
            assert result["source_count"] == 2
            # Both sources should have found content
            for src in result["sources"]:
                assert "Source content" in src["snippet"]

    async def test_batch_metadata_store_method(self):
        """Direct test of VersionedArtifactStore.read_metadata_batch."""
        with tempfile.TemporaryDirectory() as tmp:
            db_path = os.path.join(tmp, "aip.db")
            store = VersionedArtifactStore(db_path)
            await store.initialize()

            # Write some artifacts
            for i in range(5):
                await store.write(
                    f"ask:test_{i}",
                    f"Content {i}",
                    {"index": i, "artifact_type": "test"},
                )

            # Batch read
            result = await store.read_metadata_batch(
                ["ask:test_0", "ask:test_2", "ask:test_4", "ask:nonexistent"]
            )

            assert len(result) == 3  # nonexistent omitted
            assert "ask:test_0" in result
            assert "ask:test_2" in result
            assert "ask:test_4" in result
            assert result["ask:test_0"]["index"] == 0

    async def test_batch_read_with_metadata_store_method(self):
        """Direct test of VersionedArtifactStore.read_with_metadata_batch."""
        with tempfile.TemporaryDirectory() as tmp:
            db_path = os.path.join(tmp, "aip.db")
            store = VersionedArtifactStore(db_path)
            await store.initialize()

            for i in range(3):
                await store.write(
                    f"ask:test_{i}",
                    f"Content {i}",
                    {"index": i},
                )

            result = await store.read_with_metadata_batch(
                ["ask:test_0", "ask:test_1", "ask:nonexistent"]
            )

            assert len(result) == 2
            content, metadata = result["ask:test_0"]
            assert content == "Content 0"
            assert metadata["index"] == 0


# ---------------------------------------------------------------------------
# Review show — honest export eligibility
# ---------------------------------------------------------------------------


class TestReviewShowHonestExportEligibility:
    """review_show must honestly report export eligibility — only APPROVED is truly eligible."""

    async def test_generated_shows_requires_force(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            result = await review_show(aid, stores)

            assert result["export_eligible"] is False  # Not APPROVED
            assert result["export_requires_force"] is True
            assert result["export_warn"] is True

    async def test_approved_shows_eligible(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)
            await review_approve(aid, stores)

            result = await review_show(aid, stores)

            assert result["export_eligible"] is True
            assert result["export_requires_force"] is False

    async def test_rejected_shows_blocked(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)
            await review_reject(aid, stores, note="Bad")

            result = await review_show(aid, stores)

            assert result["export_eligible"] is False
            assert result["export_blocked"] is True
            assert result["export_requires_force"] is True


# ---------------------------------------------------------------------------
# Dogfood gate — no silent bypasses
# ---------------------------------------------------------------------------


class TestDogfoodGate:
    """Dogfood gate: normal export only exports APPROVED; every bypass is loudly recorded."""

    async def test_every_force_export_has_audit_trail(self):
        """Every force-exported artifact must have a corresponding force_export event."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)

            # Create and force-export multiple non-approved artifacts
            for i in range(3):
                aid = await _create_project_and_artifact(
                    stores,
                    artifact_id=f"ask:force_{i}",
                    content=f"Force-exported answer {i}",
                )
                out_path = os.path.join(tmp, f"artifact_{i}.md")
                result = await export_artifact(
                    aid, out_path, stores, force=True, force_reason=f"Batch debug export #{i}"
                )
                assert "error" not in result

            # Check that every force-exported artifact has an audit event
            for i in range(3):
                events = await stores.event_store.query(
                    artifact_id=f"ask:force_{i}",
                    event_type="force_export",
                )
                assert len(events) >= 1, f"Missing audit event for ask:force_{i}"

    async def test_approved_export_no_bypass_recorded(self):
        """APPROVED export should not generate any bypass/override records."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)
            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores)

            assert "error" not in result
            assert "force_bypass" not in result
            assert "audit_recorded" not in result

            # No force_export events
            events = await stores.event_store.query(event_type="force_export")
            assert len(events) == 0

    async def test_force_export_markdown_includes_override_notice(self):
        """Force-exported markdown should contain a SOVEREIGN OVERRIDE notice."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            out_path = os.path.join(tmp, "artifact.md")
            await export_artifact(aid, out_path, stores, force=True, force_reason="Test")

            with open(out_path) as f:
                content = f.read()

            assert "force_export: true" in content
            assert "SOVEREIGN OVERRIDE" in content

    async def test_project_export_no_rejected_artifacts_ever(self):
        """REJECTED artifacts must NEVER appear in project exports, even with --include-unreviewed."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid1 = await _create_project_and_artifact(
                stores, artifact_id="ask:approved1", content="Good answer"
            )
            aid2 = await _create_project_and_artifact(
                stores, artifact_id="ask:rejected1", content="Bad answer"
            )
            await review_approve(aid1, stores)
            await review_reject(aid2, stores, note="Rejected")

            out_path = os.path.join(tmp, "project_export.md")
            result = await export_project(
                "test_project", out_path, stores, include_unreviewed=True
            )

            assert "error" not in result

            with open(out_path) as f:
                content = f.read()

            # Good answer should be present
            assert "Good answer" in content
            # Bad answer should NEVER appear
            assert "Bad answer" not in content


# ---------------------------------------------------------------------------
# CLI registration and option tests
# ---------------------------------------------------------------------------


class TestCLIExportGateOptions:
    """Tests for CLI export command options (Chunk 7 additions)."""

    def test_export_artifact_has_reason_option(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "artifact", "--help"])
        assert result.exit_code == 0
        assert "--reason" in result.output

    def test_export_artifact_has_yes_option(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "artifact", "--help"])
        assert result.exit_code == 0
        assert "--yes" in result.output

    def test_export_project_has_reason_option(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "project", "--help"])
        assert result.exit_code == 0
        assert "--reason" in result.output

    def test_export_project_has_yes_option(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "project", "--help"])
        assert result.exit_code == 0
        assert "--yes" in result.output

    def test_force_help_mentions_emergency_debug(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "artifact", "--help"])
        assert result.exit_code == 0
        # --force should mention EMERGENCY/DEBUG
        assert "EMERGENCY" in result.output or "emergency" in result.output.lower()

    def test_include_unreviewed_help_mentions_sovereign_override(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "project", "--help"])
        assert result.exit_code == 0
        # --include-unreviewed should mention sovereign override or audit
        output_lower = result.output.lower()
        assert "sovereign" in output_lower or "audit" in output_lower
