"""Tests for review, approve, reject, and export pipeline.

Verifies the full review/export vertical slice:
- review list shows artifacts generated by ask --save-artifact
- review show displays content and lifecycle state
- review sources displays source links from the ask pipeline
- approve transitions generated artifact through existing lifecycle correctly
- approve refuses empty artifact
- approve handles broken/missing source links according to policy
- reject stores reviewer note and preserves artifact
- needs-revision stores instruction and preserves artifact
- review actions record event/trace entries
- export artifact markdown writes content and metadata
- export artifact includes source/provenance footer
- export refuses rejected artifact by default
- export warns/refuses unapproved artifact according to policy
- export project includes approved/canonical artifacts
- export project excludes rejected artifacts by default
- export project excludes unreviewed/generated artifacts by default
- missing artifact returns clear failure
- missing project returns clear failure
- export creates parent directories
- no fake success on write failure

Uses real persistent stores (SQLite) to verify that review/export
reads from the same stores that ingest and ask wrote to.
"""

from __future__ import annotations

import os
import tempfile

import pytest

from aip.adapter.artifact_store_versioned import VersionedArtifactStore
from aip.adapter.ecs_store_persistent import PersistentEcsStore
from aip.adapter.event_store_queryable import QueryableEventStore
from aip.adapter.project.sqlite_project_store import SqliteProjectStore
from aip.orchestration.review_export_pipeline import (
    ReviewExportStores,
    export_artifact,
    export_project,
    review_approve,
    review_list,
    review_needs_revision,
    review_reject,
    review_show,
    review_sources,
)


# ---------------------------------------------------------------------------
# Helpers: create test stores with a generated artifact
# ---------------------------------------------------------------------------


async def _create_test_stores(tmp_dir: str) -> ReviewExportStores:
    """Create ReviewExportStores with real persistent SQLite stores."""
    db_path = os.path.join(tmp_dir, "aip.db")

    artifact_store = VersionedArtifactStore(db_path)
    await artifact_store.initialize()

    event_store = QueryableEventStore(db_path)
    await event_store.initialize()

    project_store = SqliteProjectStore(db_path)
    await project_store.initialize()

    ecs_store = PersistentEcsStore(db_path, event_store=event_store)
    await ecs_store.initialize()

    return ReviewExportStores(
        artifact_store=artifact_store,
        ecs_store=ecs_store,
        event_store=event_store,
        project_store=project_store,
    )


async def _create_project_and_artifact(
    stores: ReviewExportStores,
    project_name: str = "test_project",
    artifact_id: str = "ask:abc123test",
    content: str = "This is a generated answer about AIP architecture.",
    source_ids: list[str] | None = None,
    source_types: list[str] | None = None,
    empty: bool = False,
) -> str:
    """Create a project and a GENERATED artifact (simulating ask --save-artifact).

    Returns the artifact_id.
    """
    # Create project
    await stores.project_store.create_project(project_name, project_name, domain=project_name)

    # Write artifact
    metadata = {
        "artifact_type": "ask_answer",
        "project_id": project_name,
        "project_name": project_name,
        "prompt": "What is the AIP architecture?",
        "model_slot": "synthesis",
        "model_name": "test-model",
        "source_ids": source_ids if source_ids is not None else ["chunk:conv1:0", "chunk:conv1:1"],
        "source_types": source_types if source_types is not None else ["conversation_chunk", "conversation_chunk"],
        "session_id": "ask:test-session",
        "generated_at": "2025-01-15T10:00:00+00:00",
    }

    artifact_content = "" if empty else content
    await stores.artifact_store.write(artifact_id, artifact_content, metadata)

    # ECS transition: None → GENERATED
    await stores.ecs_store.transition(
        artifact_id=artifact_id,
        from_state=None,
        to_state="GENERATED",
        actor="ask_pipeline",
        reason="Generated by ask pipeline — pending DEFINER review",
    )

    return artifact_id


# ---------------------------------------------------------------------------
# Test 1: review list shows artifacts generated by ask --save-artifact
# ---------------------------------------------------------------------------


class TestReviewList:
    """Test 1: review list shows artifacts generated by ask --save-artifact."""

    async def test_list_shows_generated_artifacts(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            await _create_project_and_artifact(stores)

            result = await review_list("test_project", stores)

            assert "error" not in result
            assert len(result["artifacts"]) >= 1
            art = result["artifacts"][0]
            assert art["lifecycle_state"] == "GENERATED"
            assert art["source_count"] == 2
            assert art["model_slot"] == "synthesis"


# ---------------------------------------------------------------------------
# Test 2: review show displays content and lifecycle state
# ---------------------------------------------------------------------------


class TestReviewShow:
    """Test 2: review show displays content and lifecycle state."""

    async def test_show_displays_content_and_state(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            result = await review_show(aid, stores)

            assert "error" not in result
            assert result["lifecycle_state"] == "GENERATED"
            assert "AIP architecture" in result["content"]
            assert result["source_count"] == 2
            assert result["model_slot"] == "synthesis"
            assert result["export_warn"] is True  # Unreviewed


# ---------------------------------------------------------------------------
# Test 3: review sources displays source links from the ask pipeline
# ---------------------------------------------------------------------------


class TestReviewSources:
    """Test 3: review sources displays source links from the ask pipeline."""

    async def test_sources_displays_links(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            source_ids = ["chunk:conv1:0", "chunk:conv1:1"]
            source_types = ["conversation_chunk", "conversation_chunk"]
            aid = await _create_project_and_artifact(
                stores, source_ids=source_ids, source_types=source_types
            )

            result = await review_sources(aid, stores)

            assert "error" not in result
            assert result["source_count"] == 2
            assert len(result["sources"]) == 2
            assert result["sources"][0]["source_id"] == "chunk:conv1:0"
            assert result["sources"][0]["source_type"] == "conversation_chunk"


# ---------------------------------------------------------------------------
# Test 4: approve transitions generated artifact through existing lifecycle correctly
# ---------------------------------------------------------------------------


class TestApproveTransition:
    """Test 4: approve transitions GENERATED → REVIEWED → APPROVED correctly."""

    async def test_approve_full_lifecycle(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            result = await review_approve(aid, stores)

            assert "error" not in result
            assert result["lifecycle_state"] == "APPROVED"
            assert result["previous_state"] == "GENERATED"
            assert result["canonical_written"] is True

            # Verify ECS state
            state = await stores.ecs_store.current_state(aid)
            assert state == "APPROVED"


# ---------------------------------------------------------------------------
# Test 5: approve refuses empty artifact
# ---------------------------------------------------------------------------


class TestApproveEmpty:
    """Test 5: approve refuses empty artifact."""

    async def test_approve_empty_artifact(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores, empty=True)

            result = await review_approve(aid, stores)

            assert "error" in result
            assert result["error"]["code"] == "EMPTY_CONTENT"

            # Verify state hasn't changed
            state = await stores.ecs_store.current_state(aid)
            assert state == "GENERATED"


# ---------------------------------------------------------------------------
# Test 6: approve handles broken/missing source links according to policy
# ---------------------------------------------------------------------------


class TestApproveNoSources:
    """Test 6: approve handles missing source links — ask_answer requires sources."""

    async def test_approve_no_sources_ask_answer(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(
                stores, source_ids=[], source_types=[]
            )

            result = await review_approve(aid, stores)

            assert "error" in result
            assert result["error"]["code"] == "NO_SOURCES"


# ---------------------------------------------------------------------------
# Test 7: reject stores reviewer note and preserves artifact
# ---------------------------------------------------------------------------


class TestReject:
    """Test 7: reject stores reviewer note and preserves artifact."""

    async def test_reject_preserves_artifact(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            result = await review_reject(aid, stores, note="Not grounded in sources")

            assert "error" not in result
            assert result["lifecycle_state"] == "REJECTED"
            assert result["note"] == "Not grounded in sources"
            assert result["artifact_preserved"] is True

            # Verify artifact still exists and has content
            content = await stores.artifact_store.read(aid)
            assert "AIP architecture" in content

            # Verify source links still in metadata
            metadata = await stores.artifact_store.read_metadata(aid)
            assert len(metadata.get("source_ids", [])) == 2


# ---------------------------------------------------------------------------
# Test 8: needs-revision stores instruction and preserves artifact
# ---------------------------------------------------------------------------


class TestNeedsRevision:
    """Test 8: needs-revision stores instruction and preserves artifact."""

    async def test_needs_revision_preserves_artifact(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            result = await review_needs_revision(
                aid, stores, instruction="Add more specific architecture details"
            )

            assert "error" not in result
            assert result["lifecycle_state"] == "GENERATED"  # Unchanged
            assert result["instruction"] == "Add more specific architecture details"
            assert result["artifact_preserved"] is True

            # Verify artifact still exists
            content = await stores.artifact_store.read(aid)
            assert "AIP architecture" in content


# ---------------------------------------------------------------------------
# Test 9: review actions record event/trace entries
# ---------------------------------------------------------------------------


class TestReviewEvents:
    """Test 9: review actions record event/trace entries."""

    async def test_approve_records_event(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            await review_approve(aid, stores)

            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="review_verdict",
            )
            assert len(events) >= 1
            verdict_event = events[0]
            assert verdict_event.metadata.get("verdict") == "APPROVED"

    async def test_reject_records_event(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            await review_reject(aid, stores, note="Quality insufficient")

            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="review_verdict",
            )
            assert len(events) >= 1
            verdict_event = events[0]
            assert verdict_event.metadata.get("verdict") == "REJECTED"

    async def test_needs_revision_records_event(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            await review_needs_revision(aid, stores, instruction="Expand answer")

            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="review_verdict",
            )
            assert len(events) >= 1
            verdict_event = events[0]
            assert verdict_event.metadata.get("verdict") == "NEEDS_REVISION"


# ---------------------------------------------------------------------------
# Test 10: export artifact markdown writes content and metadata
# ---------------------------------------------------------------------------


class TestExportArtifact:
    """Test 10: export artifact markdown writes content and metadata."""

    async def test_export_writes_markdown(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            # Approve first so export doesn't warn
            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "exports", "artifact.md")
            result = await export_artifact(aid, out_path, stores)

            assert "error" not in result
            assert os.path.exists(out_path)
            assert result["bytes_written"] > 0

            with open(out_path) as f:
                content = f.read()
            # Frontmatter present
            assert "artifact_id:" in content
            assert "lifecycle_state: APPROVED" in content
            # Artifact content present
            assert "AIP architecture" in content


# ---------------------------------------------------------------------------
# Test 11: export artifact includes source/provenance footer
# ---------------------------------------------------------------------------


class TestExportProvenance:
    """Test 11: export artifact includes source/provenance footer."""

    async def test_export_includes_provenance(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "artifact.md")
            await export_artifact(aid, out_path, stores)

            with open(out_path) as f:
                content = f.read()
            assert "Provenance" in content
            assert "chunk:conv1:0" in content
            assert "conversation_chunk" in content


# ---------------------------------------------------------------------------
# Test 12: export refuses rejected artifact by default
# ---------------------------------------------------------------------------


class TestExportRejected:
    """Test 12: export refuses rejected artifact by default."""

    async def test_export_rejected_blocked(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            await review_reject(aid, stores, note="Bad quality")

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores)

            assert "error" in result
            assert result["error"]["code"] == "REJECTED_ARTIFACT"
            assert not os.path.exists(out_path)


# ---------------------------------------------------------------------------
# Test 13: export warns/refuses unapproved artifact according to policy
# ---------------------------------------------------------------------------


class TestExportUnapproved:
    """Test 13: export refuses unapproved (GENERATED) artifact without force."""

    async def test_export_generated_blocked(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores)

            assert "error" in result
            assert result["error"]["code"] == "UNREVIEWED_ARTIFACT"

    async def test_export_generated_with_force(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)

            out_path = os.path.join(tmp, "artifact.md")
            result = await export_artifact(aid, out_path, stores, force=True)

            assert "error" not in result
            assert os.path.exists(out_path)


# ---------------------------------------------------------------------------
# Test 14: export project includes approved/canonical artifacts
# ---------------------------------------------------------------------------


class TestExportProjectApproved:
    """Test 14: export project includes approved/canonical artifacts."""

    async def test_export_project_approved_only(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid1 = await _create_project_and_artifact(
                stores, artifact_id="ask:approved1", content="Approved answer 1"
            )
            await review_approve(aid1, stores)

            out_path = os.path.join(tmp, "project_export.md")
            result = await export_project("test_project", out_path, stores)

            assert "error" not in result
            assert result["artifacts_exported"] >= 1

            with open(out_path) as f:
                content = f.read()
            assert "Approved answer 1" in content


# ---------------------------------------------------------------------------
# Test 15: export project excludes rejected artifacts by default
# ---------------------------------------------------------------------------


class TestExportProjectExcludesRejected:
    """Test 15: export project excludes rejected artifacts by default."""

    async def test_export_project_no_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid1 = await _create_project_and_artifact(
                stores, artifact_id="ask:good1", content="Good answer"
            )
            aid2 = await _create_project_and_artifact(
                stores, artifact_id="ask:bad1", content="Bad answer"
            )

            # Approve first, reject second
            await review_approve(aid1, stores)
            await review_reject(aid2, stores, note="Not acceptable")

            out_path = os.path.join(tmp, "project_export.md")
            result = await export_project("test_project", out_path, stores)

            assert "error" not in result

            with open(out_path) as f:
                content = f.read()
            # Approved artifact should be present
            assert "Good answer" in content
            # Rejected artifact should NOT be present
            assert "Bad answer" not in content


# ---------------------------------------------------------------------------
# Test 16: export project excludes unreviewed/generated artifacts by default
# ---------------------------------------------------------------------------


class TestExportProjectExcludesUnreviewed:
    """Test 16: export project excludes unreviewed/generated artifacts by default."""

    async def test_export_project_no_unreviewed(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid1 = await _create_project_and_artifact(
                stores, artifact_id="ask:unreviewed1", content="Unreviewed answer"
            )
            # Don't approve — leave in GENERATED state

            out_path = os.path.join(tmp, "project_export.md")
            result = await export_project("test_project", out_path, stores)

            assert result.get("artifacts_exported", 0) == 0


# ---------------------------------------------------------------------------
# Test 17: missing artifact returns clear failure
# ---------------------------------------------------------------------------


class TestMissingArtifact:
    """Test 17: missing artifact returns clear failure."""

    async def test_show_missing_artifact(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)

            result = await review_show("nonexistent:artifact", stores)
            assert "error" in result
            assert result["error"]["code"] == "NOT_FOUND"

    async def test_approve_missing_artifact(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)

            result = await review_approve("nonexistent:artifact", stores)
            assert "error" in result
            assert result["error"]["code"] == "NOT_FOUND"

    async def test_export_missing_artifact(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)

            result = await export_artifact(
                "nonexistent:artifact", os.path.join(tmp, "out.md"), stores, force=True
            )
            assert "error" in result
            assert result["error"]["code"] == "NOT_FOUND"


# ---------------------------------------------------------------------------
# Test 18: missing project returns clear failure
# ---------------------------------------------------------------------------


class TestMissingProject:
    """Test 18: missing project returns clear failure."""

    async def test_list_missing_project(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)

            result = await review_list("nonexistent_project", stores)
            assert "error" in result
            assert result["error"]["code"] == "NOT_FOUND"

    async def test_export_missing_project(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)

            out_path = os.path.join(tmp, "project_export.md")
            result = await export_project("nonexistent_project", out_path, stores)
            assert "error" in result
            assert result["error"]["code"] == "NOT_FOUND"


# ---------------------------------------------------------------------------
# Test 19: export creates parent directories
# ---------------------------------------------------------------------------


class TestExportCreatesDirectories:
    """Test 19: export creates parent directories if needed."""

    async def test_export_creates_parent_dirs(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)
            await review_approve(aid, stores)

            # Use a deeply nested path that doesn't exist
            out_path = os.path.join(tmp, "deep", "nested", "dir", "artifact.md")
            result = await export_artifact(aid, out_path, stores)

            assert "error" not in result
            assert os.path.exists(out_path)


# ---------------------------------------------------------------------------
# Test 20: no fake success on write failure
# ---------------------------------------------------------------------------


class TestNoFakeSuccess:
    """Test 20: no fake success on write failure."""

    async def test_export_write_failure(self):
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_test_stores(tmp)
            aid = await _create_project_and_artifact(stores)
            await review_approve(aid, stores)

            # Create a directory where the output file should be —
            # this makes the open() fail because it's a directory, not a file
            out_path = os.path.join(tmp, "artifact.md")
            os.makedirs(out_path, exist_ok=True)  # Make it a directory

            result = await export_artifact(aid, out_path, stores)

            # Should return an error, not fake success
            assert "error" in result
            assert result["error"]["code"] == "WRITE_FAILED"


# ---------------------------------------------------------------------------
# CLI registration tests
# ---------------------------------------------------------------------------


class TestCLIReviewExport:
    """Tests for CLI command registration."""

    def test_review_command_registered(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "--help"])
        assert result.exit_code == 0
        assert "Review" in result.output

    def test_review_list_subcommand(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "list", "--help"])
        assert result.exit_code == 0
        assert "--project" in result.output

    def test_review_show_subcommand(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "show", "--help"])
        assert result.exit_code == 0
        assert "ARTIFACT_ID" in result.output

    def test_review_sources_subcommand(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "sources", "--help"])
        assert result.exit_code == 0

    def test_review_approve_subcommand(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "approve", "--help"])
        assert result.exit_code == 0

    def test_review_reject_subcommand(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "reject", "--help"])
        assert result.exit_code == 0
        assert "--note" in result.output

    def test_review_needs_revision_subcommand(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "needs-revision", "--help"])
        assert result.exit_code == 0
        assert "--note" in result.output

    def test_export_command_registered(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "--help"])
        assert result.exit_code == 0
        assert "Export" in result.output

    def test_export_artifact_subcommand(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "artifact", "--help"])
        assert result.exit_code == 0
        assert "--out" in result.output
        assert "--force" in result.output

    def test_export_project_subcommand(self):
        from click.testing import CliRunner
        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "project", "--help"])
        assert result.exit_code == 0
        assert "--out" in result.output
        assert "--include-unreviewed" in result.output
