"""Tests for Sprint 11 — Artifact Lifecycle and Review Sprint.

Verifies:
- Artifact creation from content (standalone, not just from ask)
- Artifact metadata (title, description, tags, sources, state, review history)
- Reviewer notes (add note without changing state)
- Force-export discipline (audit events, never looks like normal export)
- Normal export records artifact_exported event
- Export targets: markdown and plain text
- Artifact ledger (full transition and event history)
- Review queue dashboard (counts by state, recent activity, force-export exceptions)
- CLI registration for new commands

Gate: AIP can produce useful documents while preserving the DEFINER's approval authority.
"""

from __future__ import annotations

import os
import tempfile

from aip.foundation.schemas.artifact import (
    ArtifactMetadata,
    ReviewQueueSummary,
)
from aip.orchestration.artifact_lifecycle import (
    ArtifactLifecycleStores,
    artifact_create,
    artifact_ledger,
    create_artifact_lifecycle_stores,
    review_add_note,
    review_dashboard,
)
from aip.orchestration.review_export_pipeline import (
    ReviewExportStores,
    create_review_export_stores,
    export_artifact,
    export_project,
    review_approve,
    review_reject,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


async def _create_lifecycle_stores(tmp_dir: str) -> ArtifactLifecycleStores:
    """Create ArtifactLifecycleStores with real persistent SQLite stores."""
    db_path = os.path.join(tmp_dir, "aip.db")
    return await create_artifact_lifecycle_stores(db_path)


async def _create_export_stores(tmp_dir: str) -> ReviewExportStores:
    """Create ReviewExportStores with real persistent SQLite stores."""
    db_path = os.path.join(tmp_dir, "aip.db")
    return await create_review_export_stores(db_path)


async def _create_project(stores, project_name: str = "test_project"):
    """Create a project in the project store."""
    await stores.project_store.create_project(project_name, project_name, domain=project_name)


async def _seed_artifact(
    stores: ArtifactLifecycleStores,
    artifact_id: str = "ask:seed123",
    content: str = "Seeded artifact content about AIP architecture.",
    project_name: str = "test_project",
    source_ids: list[str] | None = None,
) -> str:
    """Seed a GENERATED artifact for testing."""
    await _create_project(stores, project_name)

    metadata = {
        "artifact_type": "ask_answer",
        "project_id": project_name,
        "project_name": project_name,
        "title": content[:80],
        "prompt": "What is the AIP architecture?",
        "model_slot": "synthesis",
        "model_name": "test-model",
        "source_ids": source_ids or ["chunk:conv1:0"],
        "source_types": ["conversation_chunk"],
        "session_id": "session:test",
        "generated_at": "2025-01-15T10:00:00+00:00",
    }

    await stores.artifact_store.write(artifact_id, content, metadata)
    await stores.ecs_store.transition(
        artifact_id=artifact_id,
        from_state=None,
        to_state="GENERATED",
        actor="ask_pipeline",
        reason="Generated by ask pipeline — pending DEFINER review",
    )

    return artifact_id


# ---------------------------------------------------------------------------
# Chunk 1: Artifact creation
# ---------------------------------------------------------------------------


class TestArtifactCreate:
    """Test 1: User can turn content into an artifact."""

    async def test_create_artifact_basic(self):
        """artifact_create creates a new artifact with GENERATED state."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            result = await artifact_create(
                content="This is a manually created document about AIP.",
                stores=stores,
                title="AIP Overview",
                description="An overview document",
                tags=["architecture", "overview"],
            )

            assert "error" not in result
            assert result["lifecycle_state"] == "GENERATED"
            assert result["artifact_type"] == "manual_document"
            assert result["title"] == "AIP Overview"
            assert result["source_count"] == 0

            # Verify artifact exists in store
            content = await stores.artifact_store.read(result["artifact_id"])
            assert "manually created document" in content

    async def test_create_artifact_with_project(self):
        """artifact_create associates artifact with a project."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            await _create_project(stores, "my_project")

            result = await artifact_create(
                content="Project-specific artifact content",
                stores=stores,
                title="Project Doc",
                project_name="my_project",
            )

            assert "error" not in result
            # Verify project association in metadata
            metadata = await stores.artifact_store.read_metadata(result["artifact_id"])
            assert metadata["project_name"] == "my_project"

    async def test_create_artifact_with_sources(self):
        """artifact_create records source links."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)

            result = await artifact_create(
                content="Artifact referencing sources",
                stores=stores,
                source_ids=["chunk:conv1:0", "chunk:conv2:1"],
                source_types=["conversation_chunk", "conversation_chunk"],
            )

            assert "error" not in result
            assert result["source_count"] == 2

    async def test_create_artifact_empty_content_rejected(self):
        """artifact_create rejects empty content."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            result = await artifact_create(content="", stores=stores)

            assert "error" in result
            assert result["error"]["code"] == "EMPTY_CONTENT"

    async def test_create_artifact_records_creation_event(self):
        """artifact_create records an artifact_created event in EventStore."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            result = await artifact_create(
                content="Content for event test",
                stores=stores,
                title="Event Test Doc",
            )

            events = await stores.event_store.query(
                artifact_id=result["artifact_id"],
                event_type="artifact_created",
            )
            assert len(events) >= 1
            assert events[0].event_type == "artifact_created"
            assert events[0].metadata.get("title") == "Event Test Doc"

    async def test_create_artifact_nonexistent_project(self):
        """artifact_create returns error for non-existent project."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            result = await artifact_create(
                content="Content",
                stores=stores,
                project_name="nonexistent_project",
            )

            assert "error" in result
            assert result["error"]["code"] == "NOT_FOUND"


# ---------------------------------------------------------------------------
# Chunk 2: Review UX — reviewer notes
# ---------------------------------------------------------------------------


class TestReviewerNotes:
    """Test 2: User can add reviewer notes without changing state."""

    async def test_add_note_preserves_state(self):
        """review_add_note records a note but doesn't change ECS state."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            aid = await _seed_artifact(stores)

            result = await review_add_note(aid, stores, note="Check source grounding before approving")

            assert "error" not in result
            assert result["lifecycle_state"] == "GENERATED"  # Unchanged
            assert result["note"] == "Check source grounding before approving"
            assert result["actor"] == "definer"

    async def test_add_note_records_event(self):
        """review_add_note writes a reviewer_note event to EventStore."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            aid = await _seed_artifact(stores)

            await review_add_note(aid, stores, note="Consider expanding section 2")

            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="reviewer_note",
            )
            assert len(events) >= 1
            assert events[0].metadata.get("note") == "Consider expanding section 2"

    async def test_add_note_to_missing_artifact(self):
        """review_add_note returns error for non-existent artifact."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            result = await review_add_note("nonexistent:artifact", stores, note="Note")

            assert "error" in result
            assert result["error"]["code"] == "NOT_FOUND"

    async def test_multiple_notes_on_same_artifact(self):
        """Multiple reviewer notes can be added to the same artifact."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            aid = await _seed_artifact(stores)

            await review_add_note(aid, stores, note="First observation")
            await review_add_note(aid, stores, note="Second observation")

            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="reviewer_note",
            )
            assert len(events) >= 2


# ---------------------------------------------------------------------------
# Chunk 3: Force-export discipline / Normal export trace
# ---------------------------------------------------------------------------


class TestExportAuditTrail:
    """Test 3: Every export — normal or force — has a traceable event."""

    async def test_normal_export_records_artifact_exported_event(self):
        """Normal export of APPROVED artifact records artifact_exported event."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_export_stores(tmp)
            await _create_project(stores, "test_project")

            # Create and approve an artifact
            aid = "ask:export_test"
            metadata = {
                "artifact_type": "ask_answer",
                "project_id": "test_project",
                "project_name": "test_project",
                "prompt": "Test export",
                "source_ids": ["chunk:conv1:0"],
                "source_types": ["conversation_chunk"],
                "generated_at": "2025-01-15T10:00:00+00:00",
            }
            await stores.artifact_store.write(aid, "Export test content", metadata)
            await stores.ecs_store.transition(aid, None, "GENERATED", "ask_pipeline", "Created")

            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "export.md")
            result = await export_artifact(aid, out_path, stores, format="markdown")

            assert "error" not in result

            # Verify artifact_exported event was recorded
            events = await stores.event_store.query(
                artifact_id=aid,
                event_type="artifact_exported",
            )
            assert len(events) >= 1
            assert events[0].metadata.get("format") == "markdown"

    async def test_force_export_creates_force_event_not_artifact_exported(self):
        """Force-export creates a force_export event, not artifact_exported."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_export_stores(tmp)
            await _create_project(stores, "test_project")

            aid = "ask:force_test"
            metadata = {
                "artifact_type": "ask_answer",
                "project_id": "test_project",
                "project_name": "test_project",
                "source_ids": ["chunk:conv1:0"],
                "source_types": ["conversation_chunk"],
                "generated_at": "2025-01-15T10:00:00+00:00",
            }
            await stores.artifact_store.write(aid, "Force test content", metadata)
            await stores.ecs_store.transition(aid, None, "GENERATED", "ask_pipeline", "Created")

            out_path = os.path.join(tmp, "force_export.md")
            result = await export_artifact(aid, out_path, stores, force=True, force_reason="Debug")

            assert "error" not in result
            assert result.get("force_bypass") is True

            # Should have force_export event
            force_events = await stores.event_store.query(
                artifact_id=aid,
                event_type="force_export",
            )
            assert len(force_events) >= 1

            # Should NOT have artifact_exported event (force is different)
            normal_events = await stores.event_store.query(
                artifact_id=aid,
                event_type="artifact_exported",
            )
            assert len(normal_events) == 0

    async def test_force_export_never_looks_like_normal(self):
        """Force-export result includes force_bypass markers that normal export doesn't."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_export_stores(tmp)
            await _create_project(stores, "test_project")

            # Create two artifacts: one approved, one not
            aid_normal = "ask:normal_export"
            aid_force = "ask:force_export"
            for aid in [aid_normal, aid_force]:
                metadata = {
                    "artifact_type": "ask_answer",
                    "project_id": "test_project",
                    "project_name": "test_project",
                    "source_ids": ["chunk:conv1:0"],
                    "source_types": ["conversation_chunk"],
                    "generated_at": "2025-01-15T10:00:00+00:00",
                }
                await stores.artifact_store.write(aid, f"Content for {aid}", metadata)
                await stores.ecs_store.transition(aid, None, "GENERATED", "ask_pipeline", "Created")

            await review_approve(aid_normal, stores)

            # Normal export
            normal_result = await export_artifact(aid_normal, os.path.join(tmp, "normal.md"), stores)
            # Force export
            force_result = await export_artifact(
                aid_force, os.path.join(tmp, "force.md"), stores, force=True, force_reason="Emergency"
            )

            # Normal export should NOT have force markers
            assert "force_bypass" not in normal_result
            assert "audit_recorded" not in normal_result

            # Force export MUST have force markers
            assert force_result["force_bypass"] is True
            assert force_result["force_bypass_state"] == "GENERATED"
            assert force_result["audit_recorded"] is True

            # Force-exported markdown must have SOVEREIGN OVERRIDE notice
            with open(os.path.join(tmp, "force.md")) as f:
                force_content = f.read()
            assert "SOVEREIGN OVERRIDE" in force_content
            assert "force_export: true" in force_content

            # Normal markdown must NOT have SOVEREIGN OVERRIDE notice
            with open(os.path.join(tmp, "normal.md")) as f:
                normal_content = f.read()
            assert "SOVEREIGN OVERRIDE" not in normal_content
            assert "force_export" not in normal_content


# ---------------------------------------------------------------------------
# Chunk 4: Export targets — plain text
# ---------------------------------------------------------------------------


class TestPlainTextExport:
    """Test 4: Plain text export format."""

    async def test_export_artifact_plain_text(self):
        """export_artifact produces plain text output when format='text'."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_export_stores(tmp)
            await _create_project(stores, "test_project")

            aid = "ask:text_export"
            metadata = {
                "artifact_type": "ask_answer",
                "project_id": "test_project",
                "project_name": "test_project",
                "source_ids": ["chunk:conv1:0"],
                "source_types": ["conversation_chunk"],
                "generated_at": "2025-01-15T10:00:00+00:00",
            }
            await stores.artifact_store.write(aid, "Plain text content for export", metadata)
            await stores.ecs_store.transition(aid, None, "GENERATED", "ask_pipeline", "Created")
            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "export.txt")
            result = await export_artifact(aid, out_path, stores, format="text")

            assert "error" not in result
            assert result["format"] == "text"
            assert os.path.exists(out_path)

            with open(out_path) as f:
                content = f.read()

            # Plain text format: no YAML frontmatter delimiters (--- on own line)
            # The separator uses 60 dashes on its own line, but no YAML --- blocks
            lines = content.split("\n")
            yaml_frontmatter_lines = [line.strip() for line in lines if line.strip() == "---"]
            assert len(yaml_frontmatter_lines) == 0, "Plain text should not have YAML frontmatter"
            assert "**Provenance**" not in content  # No bold markdown
            assert "Plain text content" in content
            assert "Provenance:" in content  # Plain text provenance
            assert "Source 1:" in content

    async def test_export_project_plain_text(self):
        """export_project produces plain text bundle when format='text'."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_export_stores(tmp)
            await _create_project(stores, "test_project")

            aid = "ask:proj_text"
            metadata = {
                "artifact_type": "ask_answer",
                "project_id": "test_project",
                "project_name": "test_project",
                "source_ids": ["chunk:conv1:0"],
                "source_types": ["conversation_chunk"],
                "generated_at": "2025-01-15T10:00:00+00:00",
            }
            await stores.artifact_store.write(aid, "Project text export content", metadata)
            await stores.ecs_store.transition(aid, None, "GENERATED", "ask_pipeline", "Created")
            await review_approve(aid, stores)

            out_path = os.path.join(tmp, "project_export.txt")
            result = await export_project("test_project", out_path, stores, format="text")

            assert "error" not in result
            assert result["format"] == "text"

            with open(out_path) as f:
                content = f.read()

            assert "Project text export content" in content
            assert "Artifact Index:" in content

    async def test_plain_text_force_export_has_override_notice(self):
        """Force-export in plain text includes SOVEREIGN OVERRIDE notice."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_export_stores(tmp)
            await _create_project(stores, "test_project")

            aid = "ask:force_text"
            metadata = {
                "artifact_type": "ask_answer",
                "project_id": "test_project",
                "project_name": "test_project",
                "source_ids": [],
                "source_types": [],
                "generated_at": "2025-01-15T10:00:00+00:00",
            }
            await stores.artifact_store.write(aid, "Force text export", metadata)
            await stores.ecs_store.transition(aid, None, "GENERATED", "ask_pipeline", "Created")

            out_path = os.path.join(tmp, "force.txt")
            await export_artifact(aid, out_path, stores, format="text", force=True, force_reason="Debug")

            with open(out_path) as f:
                content = f.read()

            assert "SOVEREIGN OVERRIDE" in content
            assert "FORCE_EXPORT: true" in content


# ---------------------------------------------------------------------------
# Chunk 5: Artifact ledger
# ---------------------------------------------------------------------------


class TestArtifactLedger:
    """Test 5: Every artifact transition is recorded; user can inspect who/what moved it and why."""

    async def test_ledger_shows_full_history(self):
        """artifact_ledger returns complete lifecycle timeline."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            aid = await _seed_artifact(stores)

            # Add some events
            await review_add_note(aid, stores, note="Review observation")
            await review_reject(aid, stores, note="Not good enough")

            # Need export stores for reject
            await _create_export_stores(tmp)

            result = await artifact_ledger(aid, stores)

            assert "error" not in result
            assert result["artifact_id"] == aid
            assert result["current_state"] == "REJECTED"
            assert result["event_count"] >= 3  # Created, note, reject at minimum

            # Verify ledger entries
            ledger = result["ledger"]
            assert len(ledger) >= 3

            # Check that entries have the expected structure
            for entry in ledger:
                assert "event_type" in entry
                assert "actor" in entry
                assert "timestamp" in entry

    async def test_ledger_missing_artifact(self):
        """artifact_ledger returns error for non-existent artifact."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            result = await artifact_ledger("nonexistent:artifact", stores)

            assert "error" in result
            assert result["error"]["code"] == "NOT_FOUND"

    async def test_ledger_shows_who_moved_and_why(self):
        """Ledger entries include actor and detail/reason."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            aid = await _seed_artifact(stores)

            # Add a reviewer note
            await review_add_note(aid, stores, note="Check accuracy of claims")

            result = await artifact_ledger(aid, stores)
            ledger = result["ledger"]

            # Find the reviewer_note entry
            note_entries = [e for e in ledger if e["event_type"] == "reviewer_note"]
            assert len(note_entries) >= 1
            assert note_entries[0]["actor"] == "definer"
            assert "Check accuracy" in note_entries[0]["detail"]


# ---------------------------------------------------------------------------
# Chunk 6: Review queue dashboard
# ---------------------------------------------------------------------------


class TestReviewDashboard:
    """Test 6: Review queue dashboard shows counts and activity."""

    async def test_dashboard_empty_system(self):
        """Dashboard shows zero counts for empty system."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            result = await review_dashboard(stores)

            assert result["states"]["GENERATED"] == 0
            assert result["states"]["APPROVED"] == 0
            assert result["states"]["REJECTED"] == 0
            assert result["total_active"] == 0
            assert result["total_pending_review"] == 0

    async def test_dashboard_shows_state_counts(self):
        """Dashboard correctly counts artifacts in each state."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            await _create_project(stores, "test_project")

            # Create 3 GENERATED artifacts
            for i in range(3):
                await artifact_create(
                    content=f"Artifact {i}",
                    stores=stores,
                    title=f"Doc {i}",
                    project_name="test_project",
                )

            # Approve one using export stores (same DB, different instances)
            export_stores = await _create_export_stores(tmp)
            generated_ids = await stores.ecs_store.list_by_state("GENERATED")
            if generated_ids:
                await review_approve(generated_ids[0], export_stores)
            await export_stores.close()

            # Reload ECS cache since export_stores modified the DB
            stores.ecs_store._cache_loaded = False
            await stores.ecs_store._load_state_from_db()

            result = await review_dashboard(stores)

            assert result["states"]["GENERATED"] == 2
            assert result["states"]["APPROVED"] == 1
            assert result["total_active"] == 3

    async def test_dashboard_shows_force_exports(self):
        """Dashboard shows force-export exceptions."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            await _create_project(stores, "test_project")

            # Create an artifact and force-export it
            create_result = await artifact_create(
                content="Force export test",
                stores=stores,
                title="Force Doc",
                project_name="test_project",
            )

            export_stores = await _create_export_stores(tmp)
            out_path = os.path.join(tmp, "force.md")
            await export_artifact(
                create_result["artifact_id"], out_path, export_stores, force=True, force_reason="Dashboard test"
            )
            await export_stores.close()

            # Reload ECS cache
            stores.ecs_store._cache_loaded = False
            await stores.ecs_store._load_state_from_db()

            result = await review_dashboard(stores)
            assert result["force_export_count"] >= 1

    async def test_dashboard_shows_recent_events(self):
        """Dashboard shows recent activity."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            await _create_project(stores, "test_project")

            # Create some activity
            await artifact_create(
                content="Activity test",
                stores=stores,
                title="Activity Doc",
                project_name="test_project",
            )

            result = await review_dashboard(stores)
            assert len(result["recent_events"]) >= 1

    async def test_dashboard_needs_revision_count(self):
        """Dashboard counts artifacts with NEEDS_REVISION verdict."""
        with tempfile.TemporaryDirectory() as tmp:
            stores = await _create_lifecycle_stores(tmp)
            await _create_project(stores, "test_project")

            # Create an artifact and mark it as needs-revision
            create_result = await artifact_create(
                content="Needs revision test",
                stores=stores,
                title="Revision Doc",
                project_name="test_project",
            )

            export_stores = await _create_export_stores(tmp)
            from aip.orchestration.review_export_pipeline import review_needs_revision

            await review_needs_revision(
                create_result["artifact_id"], export_stores, instruction="Please expand section 2"
            )

            result = await review_dashboard(stores)
            assert result["needs_revision_count"] >= 1


# ---------------------------------------------------------------------------
# ArtifactMetadata schema tests
# ---------------------------------------------------------------------------


class TestArtifactMetadata:
    """Test ArtifactMetadata serialization and deserialization."""

    def test_metadata_to_dict(self):
        meta = ArtifactMetadata(
            artifact_type="manual_document",
            title="My Doc",
            description="A test doc",
            tags=["test", "docs"],
            project_name="myproject",
        )
        d = meta.to_dict()
        assert d["artifact_type"] == "manual_document"
        assert d["title"] == "My Doc"
        assert d["tags"] == ["test", "docs"]

    def test_metadata_from_dict(self):
        d = {
            "artifact_type": "ask_answer",
            "title": "Test",
            "description": "Desc",
            "tags": ["a"],
            "project_id": "p1",
            "source_ids": ["s1", "s2"],
            "source_types": ["conversation_chunk", "conversation_chunk"],
            "generated_at": "2025-01-15T10:00:00+00:00",
            "custom_fields": {"extra": "value"},
        }
        meta = ArtifactMetadata.from_dict(d)
        assert meta.artifact_type == "ask_answer"
        assert len(meta.source_ids) == 2
        assert meta.custom_fields["extra"] == "value"

    def test_roundtrip(self):
        meta = ArtifactMetadata(
            artifact_type="beast_wiki",
            title="Wiki Article",
            tags=["wiki"],
            source_ids=["s1"],
            custom_fields={"priority": "high"},
        )
        d = meta.to_dict()
        meta2 = ArtifactMetadata.from_dict(d)
        assert meta2.artifact_type == meta.artifact_type
        assert meta2.tags == meta.tags
        assert meta2.custom_fields == meta.custom_fields


# ---------------------------------------------------------------------------
# ReviewQueueSummary schema tests
# ---------------------------------------------------------------------------


class TestReviewQueueSummary:
    """Test ReviewQueueSummary computed properties."""

    def test_total_active(self):
        summary = ReviewQueueSummary(
            generated_count=3,
            reviewed_count=1,
            approved_count=2,
        )
        assert summary.total_active == 6

    def test_total_pending_review(self):
        summary = ReviewQueueSummary(
            generated_count=5,
            needs_revision_count=2,
        )
        assert summary.total_pending_review == 7


# ---------------------------------------------------------------------------
# CLI registration tests
# ---------------------------------------------------------------------------


class TestCLIRegistration:
    """Test that new CLI commands are properly registered."""

    def test_artifact_command_registered(self):
        from click.testing import CliRunner

        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["artifact", "--help"])
        assert result.exit_code == 0
        assert "Artifact" in result.output or "artifact" in result.output.lower()

    def test_artifact_create_subcommand(self):
        from click.testing import CliRunner

        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["artifact", "create", "--help"])
        assert result.exit_code == 0
        assert "--title" in result.output
        assert "--project" in result.output

    def test_artifact_ledger_subcommand(self):
        from click.testing import CliRunner

        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["artifact", "ledger", "--help"])
        assert result.exit_code == 0
        assert "ARTIFACT_ID" in result.output

    def test_review_note_subcommand(self):
        from click.testing import CliRunner

        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "note", "--help"])
        assert result.exit_code == 0
        assert "--text" in result.output

    def test_review_dashboard_subcommand(self):
        from click.testing import CliRunner

        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["review", "dashboard", "--help"])
        assert result.exit_code == 0

    def test_export_text_format_option(self):
        from click.testing import CliRunner

        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "artifact", "--help"])
        assert result.exit_code == 0
        assert "text" in result.output  # Plain text format available

    def test_export_project_text_format_option(self):
        from click.testing import CliRunner

        from aip.cli.main import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["export", "project", "--help"])
        assert result.exit_code == 0
        assert "text" in result.output


# ---------------------------------------------------------------------------
# End-to-end lifecycle test
# ---------------------------------------------------------------------------


class TestFullLifecycle:
    """End-to-end test: GENERATED → REVIEWED → APPROVED → EXPORTED with full trace."""

    async def test_full_artifact_lifecycle(self):
        """Complete lifecycle: create → note → approve → export → ledger → dashboard."""
        with tempfile.TemporaryDirectory() as tmp:
            lifecycle_stores = await _create_lifecycle_stores(tmp)
            export_stores = await _create_export_stores(tmp)
            await _create_project(lifecycle_stores, "lifecycle_project")

            # 1. Create artifact
            create_result = await artifact_create(
                content=(
                    "This is a complete lifecycle test document. It demonstrates "
                    "the full GENERATED → REVIEWED → APPROVED → EXPORTED path."
                ),
                stores=lifecycle_stores,
                title="Lifecycle Test Document",
                description="Testing the full artifact lifecycle",
                tags=["test", "lifecycle"],
                project_name="lifecycle_project",
                source_ids=["chunk:conv1:0"],
                source_types=["conversation_chunk"],
            )
            assert "error" not in create_result
            aid = create_result["artifact_id"]
            assert create_result["lifecycle_state"] == "GENERATED"

            # 2. Add reviewer notes
            note_result = await review_add_note(aid, lifecycle_stores, note="Sources look solid. Minor style issues.")
            assert "error" not in note_result
            assert note_result["lifecycle_state"] == "GENERATED"  # Unchanged

            # 3. Approve (via export stores which have same DB)
            approve_result = await review_approve(aid, export_stores)
            assert "error" not in approve_result
            assert approve_result["lifecycle_state"] == "APPROVED"

            # 4. Export as markdown
            md_path = os.path.join(tmp, "lifecycle.md")
            export_result = await export_artifact(aid, md_path, export_stores, format="markdown")
            assert "error" not in export_result
            assert os.path.exists(md_path)

            # 5. Export as plain text
            txt_path = os.path.join(tmp, "lifecycle.txt")
            txt_result = await export_artifact(aid, txt_path, export_stores, format="text")
            assert "error" not in txt_result
            assert os.path.exists(txt_path)

            # 6. Invalidate ECS cache (export_stores modified DB behind lifecycle_stores' back)
            lifecycle_stores.ecs_store._cache_loaded = False
            await lifecycle_stores.ecs_store._load_state_from_db()

            # 7. Inspect ledger
            ledger_result = await artifact_ledger(aid, lifecycle_stores)
            assert "error" not in ledger_result
            assert ledger_result["current_state"] == "APPROVED"
            # Should have: artifact_created, ecs_transition (GENERATED), reviewer_note,
            # review_verdict (APPROVED), ecs_transition (REVIEWED), ecs_transition (APPROVED),
            # artifact_exported (markdown), artifact_exported (text)
            assert ledger_result["event_count"] >= 5

            # Verify specific ledger entries exist
            event_types = [e["event_type"] for e in ledger_result["ledger"]]
            assert "artifact_created" in event_types
            assert "reviewer_note" in event_types
            assert "artifact_exported" in event_types

            # 8. Dashboard should show the approved artifact
            dashboard_result = await review_dashboard(lifecycle_stores)
            assert dashboard_result["states"]["APPROVED"] >= 1
