"""LLM Query Expansion — lightweight LLM-based query expansion for retrieval.

Adds an optional LLM-based query expansion step that runs
before retrieval dispatch.  This helps ambiguous or short queries by
generating alternative phrasings, synonyms, and related terms.

The expansion uses the "fast" model slot (lightweight, low-latency model)
to minimize overhead.  It is disabled by default and must be explicitly
enabled via ``OrchestratorConfig.enable_llm_query_expansion = True``.

The expanded terms are passed to the orchestrator's existing
``expand_query()`` function, which appends them to the original query.

Design principles:
  - Optional and behind a config flag — zero overhead when disabled.
  - Uses the fast/light model slot to minimize latency.
  - Timeout-protected (default 2s) — on timeout, falls back to no expansion.
  - Returns the original query unchanged on any error.
  - Conservative expansion: 3-5 terms maximum.

Layer: orchestration.  May import foundation, stdlib.  May NOT import
adapter directly — model_provider is injected.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass
from typing import Any

try:
    from aip.logging import get_logger

    logger = get_logger(__name__)
except ImportError:
    logger = logging.getLogger(__name__)

# Default prompt for query expansion
_EXPANSION_SYSTEM_PROMPT = """You are a query expansion assistant for a knowledge retrieval system.

Given a user's search query, generate 3-5 alternative search terms that would
help find relevant information. Focus on:
- Synonyms and related terms
- Alternative phrasings of the same question
- Broader or narrower terms that might match different documents

Rules:
- Return ONLY a JSON array of strings, no other text.
- Each string should be a short phrase (1-4 words).
- Do not include the original query in the expansion.
- Do not include explanations or markdown.

Example:
Query: "how to configure knowledge graph"
Response: ["knowledge graph setup", "graph database configuration", "KG deployment steps", "graph store settings"]"""


@dataclass
class ExpansionResult:
    """Result of LLM query expansion.

    Attributes:
        original_query: The original user query.
        expanded_terms: List of expanded terms generated by the LLM.
        elapsed_ms: Time taken for the LLM call in milliseconds.
        success: Whether the expansion succeeded.
        error: Error message if expansion failed.
    """

    original_query: str
    expanded_terms: list[str] = None  # type: ignore[assignment]
    elapsed_ms: float = 0.0
    success: bool = False
    error: str = ""

    def __post_init__(self):
        if self.expanded_terms is None:
            self.expanded_terms = []


async def expand_query_with_llm(
    query: str,
    model_provider: Any = None,
    timeout_seconds: float = 2.0,
    max_terms: int = 5,
) -> ExpansionResult:
    """Expand a query using LLM to generate alternative search terms.

    Uses the "fast" model slot for low-latency expansion.  If the model
    provider is unavailable, times out, or returns invalid output, the
    expansion gracefully falls back to an empty result.

    Args:
        query: The original user query.
        model_provider: ModelSlotResolver instance (or any object with a
            ``call(slot, messages)`` async method).
        timeout_seconds: Maximum time for the LLM call (default 2s).
        max_terms: Maximum number of expanded terms to return.

    Returns:
        ExpansionResult with expanded terms or empty list on failure.
    """
    result = ExpansionResult(original_query=query)

    if model_provider is None:
        result.error = "no_model_provider"
        return result

    if not query or len(query.strip()) < 3:
        result.error = "query_too_short"
        return result

    start = time.monotonic()

    try:
        messages = [
            {"role": "system", "content": _EXPANSION_SYSTEM_PROMPT},
            {"role": "user", "content": f'Query: "{query}"'},
        ]

        # Use the "fast" model slot for expansion — low latency
        llm_result = await asyncio.wait_for(
            model_provider.call("fast", messages),
            timeout=timeout_seconds,
        )

        content = (llm_result or {}).get("content", "").strip()
        if not content:
            result.error = "empty_llm_response"
            result.elapsed_ms = (time.monotonic() - start) * 1000
            return result

        # Parse the response as a JSON array
        import json

        try:
            # Try direct parse
            terms = json.loads(content)
            if not isinstance(terms, list):
                # Try extracting from markdown
                terms = _extract_json_array(content)
        except (json.JSONDecodeError, ValueError):
            terms = _extract_json_array(content)

        # Validate and limit terms
        valid_terms = []
        for term in terms:
            if isinstance(term, str) and term.strip() and len(term.strip()) <= 50:
                valid_terms.append(term.strip())
            if len(valid_terms) >= max_terms:
                break

        result.expanded_terms = valid_terms
        result.success = len(valid_terms) > 0
        result.elapsed_ms = (time.monotonic() - start) * 1000

        if result.success:
            logger.info(
                "llm_query_expansion",
                query=query[:50],
                terms=valid_terms,
                elapsed_ms=round(result.elapsed_ms, 1),
            )
        else:
            result.error = "no_valid_terms"
            logger.warning(
                "llm_query_expansion_no_terms",
                query=query[:50],
                raw_content=content[:100],
            )

    except asyncio.TimeoutError:
        result.elapsed_ms = (time.monotonic() - start) * 1000
        result.error = "timeout"
        logger.warning(
            "llm_query_expansion_timeout",
            query=query[:50],
            timeout_s=timeout_seconds,
        )
    except asyncio.CancelledError:
        result.elapsed_ms = (time.monotonic() - start) * 1000
        result.error = "cancelled"
        logger.warning(
            "llm_query_expansion_cancelled",
            query=query[:50],
        )
    except Exception as exc:
        result.elapsed_ms = (time.monotonic() - start) * 1000
        result.error = str(exc)[:100]
        logger.warning(
            "llm_query_expansion_failed",
            query=query[:50],
            error=str(exc),
        )

    return result


def _extract_json_array(text: str) -> list:
    """Robustly extract a JSON array from an LLM response.

    Handles markdown code fences and conversational text wrapping.
    """
    import json

    if not text or not text.strip():
        return []

    s = text.strip()

    # Strip markdown code fences
    if s.startswith("```"):
        first_newline = s.find("\n")
        if first_newline != -1:
            s = s[first_newline + 1 :]
        if s.rstrip().endswith("```"):
            s = s.rstrip()[:-3].rstrip()

    # Try direct parse
    try:
        parsed = json.loads(s)
        if isinstance(parsed, list):
            return parsed
    except (json.JSONDecodeError, ValueError):
        pass

    # Fallback: find the first '[' and last ']'
    start = s.find("[")
    end = s.rfind("]")
    if start != -1 and end > start:
        try:
            parsed = json.loads(s[start : end + 1])
            if isinstance(parsed, list):
                return parsed
        except (json.JSONDecodeError, ValueError):
            pass

    return []
